### ISSUE TITLE
JobRun AR Detail View

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/pre-assembly#295] opened 2018-09-17 19:16 UTC
Front-end detail view of a `JobRun` Active Record.

Needs the following:
- [x] UI Design
- [x] Route and Controller for Model
- [x] Rspec Tests

**Comment by jmartin-sul** [comment] 2018-09-18 17:15
a bit more detail and implementation advice from #300 (which is a dupe of this):

> just a thin controller that presents the log file we output from pre-assembly.
> 
> can see this as a "view" of the `JobRun` model.  could force download if it's too big or something, maybe just always force download for implementation simplicity.  need fallback for no output location in case where user is going view a job that's unstarted/unfinished.
> 
> but from rails POV, prob easiest to implement by thinking of this as a view on the job run.

**Comment by atz** [comment] 2018-09-19 22:28
So I was already assigned and have a working branch from the ticket marked as a dupe of this one.

**Closed** 2018-09-25 21:17 UTC
Labels: DB, UI, jobs, review
