### ISSUE TITLE
Implement pre-assembly redesign

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/pre-assembly#1443] opened 2024-05-17 20:21 UTC
Designs are in the ["Text Extraction" Figma file](https://www.figma.com/design/t0npsqz5E7beMF5g3xwyGw/Text-Extraction?node-id=0-1&t=1Kyz4TCndaohM0D5-1). There are 2 versions.
1. [version with simple message design](https://www.figma.com/design/t0npsqz5E7beMF5g3xwyGw/Text-Extraction?node-id=420-1894&m=dev).
2. [version with stylish message design](https://www.figma.com/design/t0npsqz5E7beMF5g3xwyGw/Text-Extraction?node-id=692-3167&m=dev).

Can possibly be split into multiple tickets to work on simultaneously.
- [x] #1468 
- [x] #1476
- [x] #1479 
- [x] #1481  (Note: tables also appear on the "All jobs" and "All projects" pages.)

**Comment by jmartin-sul** [comment] 2024-05-29 20:52
For this work cycle, we may end up splitting off separate tickets to do parts of this work, but not the whole of it.

**Comment by jmartin-sul** [comment] 2024-06-05 20:34
If someone is only working on part of this issue, they should indicate which part they're picking up, whether just via comment on this ticket, or also via a separate narrower GH issue.

**Comment by jmartin-sul** [comment] 2024-06-10 17:15
* This might mostly end up being CSS tweaks
* People on this work should do some quick accessibility review on their PRs to make sure we don't introduce regressions UNLESS we get work done to incorporate a11y checking into the test suite (new ticket coming)

**Comment by dnoneill** [comment] 2024-06-13 19:16
Closing due to all tickets being completed.

**Closed by dnoneill** 2024-06-13 19:16 UTC
